# Generated by Django 4.0.2 on 2022-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_profile_alert_time_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alert_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
