# Generated by Django 4.0.2 on 2022-02-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_profile_alert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alert_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
