# Generated by Django 4.0.2 on 2022-02-26 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='utc_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 2, 53, 41, 539542), null=True),
        ),
    ]
