# Generated by Django 4.0.2 on 2022-02-26 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_profile_alert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 16, 54, 56, 284265, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='utc_time',
            field=models.TimeField(null=True),
        ),
    ]
