# Generated by Django 4.0.2 on 2022-02-26 19:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_profile_alert_time_alter_profile_utc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 19, 50, 34, 475559, tzinfo=utc), null=True),
        ),
    ]
