# Generated by Django 4.0.2 on 2022-02-26 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_profile_alert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alert_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 2, 26, 19, 53, 22, 427709, tzinfo=utc), null=True),
        ),
    ]
