# Generated by Django 4.0.2 on 2022-02-27 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_profile_alert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 27, 10, 38, 47, 321279, tzinfo=utc), null=True),
        ),
    ]
